config/routes.rb
Rails.application.routes.draw do
 # get 'sessions/new'
 get 'login'=>'sessions#new'
 post 'login'=> 'sessions#create'
 get 'logout'=> 'sessions#destroy'




  #get 'utilisateurs/new'
  #get 'pages/home'
  #get 'pages/aide'
  #get 'pages/contact'    #ajouter


  root 'pages#home'
  get 'aide' => 'pages#aide'
  get 'contact' => 'pages#contact'


  get 'inscription' => 'utilisateurs#new'
  resources :utilisateurs

  resources :articles,only: [:create,:destroy]
  #resources :

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end


# aide_path => '/aide'
# aide_url => 'http://localhost:3000/aide'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :utilisateur
  validates :utilisateur_id, presence: true
  validates :titre, presence: true, length: { maximum: 200 }
  validates :description, presence: true, length: { maximum: 2000 }
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
    has_many :article, dependent: :destroy

    validates :nom, presence: true, length: { maximum: 50 }
    VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                      length: { maximum: 255 },
                      format: { with: VALID_EMAIL },
                      uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  def authenticate
    unless logged_in?
      flash[:danger] = "Merci de vous connecter."
      redirect_to login_url
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate, :only=>[:create,:destroy]
  def create
    @article = utilisateur_courant.articles.build(article_params)
    if @article.save
      flash[:success] = "Article crée"
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  def destroy
  end

  private

    def article_params
      params.require(:article).permit(:titre, :description)
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @article=utilisateur_courant.article.build if logged_in?
  end

  def aide
  end

  def contact        # ajouter
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    utilisateur = Utilisateur.find_by(email: params[:session][:email].downcase)
    if utilisateur && utilisateur.authenticate(params[:session][:password])
      log_in utilisateur
      redirect_to utilisateur
    else
      flash[:danger] = 'Combinaison email/mot de passe invalide'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  before_action :authenticate, only: [:index,:edit, :update,:destroy]
  before_action :bon_utilisateur, only: [:edit, :update]
  before_action :utilisateur_admin, only: :destroy


  def index
    @utilisateurs = Utilisateur.paginate(page: params[:page], per_page: 2)
  end


  def new
    @utilisateur = Utilisateur.new
  end

  def show
    @utilisateur = Utilisateur.find(params[:id])
    @articles=@utilisateur.article
  end

  def create
    @utilisateur = Utilisateur.new(utilisateur_params)
    if @utilisateur.save
      flash[:success] = "Bienvenue!"
      redirect_to @utilisateur
    else
      render 'new'
    end
  end

  def edit
    @utilisateur = Utilisateur.find(params[:id])
  end

  def update
    @utilisateur = Utilisateur.find(params[:id])
    if @utilisateur.update(utilisateur_params)
      flash[:success] = "Profil actualisé"
      redirect_to @utilisateur
    else
      render 'edit'
    end
  end

  private

  def utilisateur_params
    params.require(:utilisateur).permit(:nom, :email, :password, :password_confirmation)
  end

  def authenticate
    unless logged_in?
      flash[:danger] = "Merci de vous connecter."
      redirect_to login_url
    end
  end

  def bon_utilisateur
    @utilisateur = Utilisateur.find(params[:id])
    redirect_to(root_url) unless @utilisateur == utilisateur_courant
  end

  def destroy
    Utilisateur.find(params[:id]).destroy
    flash[:success]="utiisateur supprime"
    redirect_to root_url

  end


  def utilisateur_admin
    @utilisateur=Utilisateur.find(params[:id])
    if not @utilisateur_courant.admin? || @utilisateur==utilisateur_courant
      redirect_to(root_url)
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  ## appelle de tous les endroits
  def log_in(utilisateur)
    session[:utilisateur_id] = utilisateur.id
  end

  def utilisateur_courant
    @utilisateur_courant ||= Utilisateur.find_by(id: session[:utilisateur_id])
    #@utilisateur_courant = @utilisateur_courant  || @utilisateur.find_by(id:session[:utilisateur_id])
  end

  def logged_in?
    !utilisateur_courant.nil?
  end

  def log_out
    session.delete(:utilisateur_id)
    @utilisateur_courant=nil
  end
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/views/articles/_article.html.erb
<li id="article-<%= article.id %>">
  <span class="utilisateur"><%= link_to article.utilisateur.nom,
                article.utilisateur %></span>
  <span class="titre"><%= article.titre %></span>
  <span class="timestamp">
    Posté il y a <%= time_ago_in_words(article.created_at) %>.
  </span>
</li>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href ="ensa.uit.ac.ma">ENSAK, Maroc.</a>
        </small>
        <nav>
            <ul>
                <li><%= link_to "Contact", contact_path %> </li>
                <li><%= link_to "Aide", aide_path %> </li>
            </ul>

        </nav>
        </footer>
       </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="#">Le Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Utilisateurs", utilisateurs_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Compte <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", utilisateur_path(utilisateur_courant) %></li>
              <li><%= link_to "Paramètres", edit_utilisateur_path(utilisateur_courant) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Se déconnecter", logout_path, method: "get" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Se connecter", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2024</title>
    <script
      src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>


      <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>


<link
rel="stylesheet" type="text/css"
href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |message_type, message|%>
      <div class="alert alert-<%= message_type %>">
        <%= message %></div>
    <%end%>
    <%= yield %>  
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/aide.html.erb
<h1>Pages#aide</h1>
<p>Find me in app/views/pages/aide.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>      

app/views/pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="article_form">
        <%= form_for(@article) do |f| %>
                 
                  <div class="col-sm-8">
          <%= f.text_field :titre, rows: 10, class: "form-control", placeholder: "Titre" %>
            </div>
                  <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Texte" %>
            </div>
                  <%= f.submit "Soumettre", class: "btn btn-primary" %>
                <% end %>
      </section>
    </aside>
  </div>
<% else %>




<div class="container">
     <div class="jumbotron">
      <h1>LE BLOG</h1>
      <p>Un blog est un type de site web – ou une partie d'un site web – utilisé pour la publication périodique et régulière d'articles, généralement succincts, et rendant compte d'une actualité autour d'un sujet donné ou d'une profession. (<a  href="https://fr.wikipedia.org/wiki/Blog">Wikipedia</a>)</p&gt;
<!--       <p><a class="btn btn-primary btn-lg" href="#" role="button">S'inscrire</a></p> -->
      <%= link_to "S'inscrire", inscription_path, class: "btn btn-lg btn-primary" %>
         </div>
 </div>

<% end %>

app/views/shared/_error_messages.html.erb
<% if @utilisateur.errors.any?%>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@utilisateur.errors.count, "error") %>.</div>

        <ul>
            <% @utilisateur.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<%end%>

app/views/utilisateurs/edit.html.erb
<h1>modification</h1>
<%= form_for(@utilisateur, :html => {class: "form-horizontal", role: "form"}) do |f| %>
       

          <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :nom %>
            </div>
            <div class="col-sm-4">
              <%= f.text_field :nom, class:"form-control",  placeholder:"Entrer votre nom"%>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :email %>
            </div>
            <div class="col-sm-4">
              <%= f.email_field :email, class:"form-control",  placeholder:"Entrer votre email"%>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :password %>
            </div>
            <div class="col-sm-4">
              <%= f.password_field :password , class:"form-control",  placeholder:"Entrer votre password"%>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :password_confirmation, "Confirmation"  %>
            </div>
            <div class="col-sm-4">
              <%= f.password_field :password_confirmation, class:"form-control",  placeholder:"Entrer votre password"%>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-4">
              <%= f.submit "modifier", class: "btn btn-primary" %>
            </div>
          </div>

    <% end %>

app/views/utilisateurs/index.html.erb
<h1>Tous les utilisateurs</h1>
<ul class='utilisateurs'>
  <% @utilisateurs.each do |utilisateur| %>
  <li>
    <%= link_to utilisateur.nom, utilisateur %>

    <% if @utilisateur_courant.admin? || utilisateur_courant == utilisateur %>
      <%= link_to "delete", utilisateur, method: :delete, data: { confirm: "Confirmer" } %>
    <% end %>
  </li>
  <% end %>
</ul>
<%= will_paginate @utilisateurs %>

app/views/utilisateurs/new.html.erb
<%= render 'shared/error_messages' %>
<h1>Inscription</h1>
<%= form_for(@utilisateur, :html => {class: "form-horizontal", role: "form"}) do |f| %>
       

          <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :nom %>
            </div>
            <div class="col-sm-4">
              <%= f.text_field :nom, class:"form-control",  placeholder:"Entrer votre nom"%>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :email %>
            </div>
            <div class="col-sm-4">
              <%= f.email_field :email, class:"form-control",  placeholder:"Entrer votre email"%>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :password %>
            </div>
            <div class="col-sm-4">
              <%= f.password_field :password , class:"form-control",  placeholder:"Entrer votre password"%>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :password_confirmation, "Confirmation"  %>
            </div>
            <div class="col-sm-4">
              <%= f.password_field :password_confirmation, class:"form-control",  placeholder:"Entrer votre password"%>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-4">
              <%= f.submit "Creer", class: "btn btn-primary" %>
            </div>
          </div>

    <% end %>

app/views/utilisateurs/show.html.erb
<%= @utilisateur.nom %>,<%= @utilisateur.email%>
<% if @utilisateur.article.any? %>
      <h3>Articles (<%= @utilisateur.article.count %>)</h3>
      <ol class="articles">
        <%= render @articles %>
      </ol>
    <% end %>